<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>preview</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Infokom.Gaming.Poker\Infokom.Gaming.Poker.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Infokom.Gaming.Poker.Texas.Benchmarks"/>
	</ItemGroup>
</Project>
