<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\BinarySerializer\BinarySerializer.csproj" />
		<ProjectReference Include="..\CSharpSerializer\CSharpSerializer.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Poker.Calc.Benchmarks" />
	</ItemGroup>
</Project>
