<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
		<AssemblyName>BinarySerializer</AssemblyName>
		<GenerateAssemblyInfo>False</GenerateAssemblyInfo>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\MemoryPools\MemoryPools.csproj" />
	</ItemGroup>
</Project>