<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
		<AssemblyName>Hand2NoteCore.HandStrength</AssemblyName>
		<GenerateAssemblyInfo>False</GenerateAssemblyInfo>
		<LangVersion>preview</LangVersion>
	</PropertyGroup>
	<PropertyGroup>
		<LangVersion>14.0</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
	</PropertyGroup>
	<PropertyGroup />
	<ItemGroup>
		<PackageReference Include="protobuf-net" Version="3.3.8" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\BinarySerializer\BinarySerializer.csproj" />
		<ProjectReference Include="..\MemoryPools\MemoryPools.csproj" />
		<ProjectReference Include="..\Poker.Calc\Poker.Calc.csproj" />
	</ItemGroup>
</Project>