using System.Numerics;

namespace Infokom.Numerics.Operators
{
	public static partial class NumberBase
	{
		extension(ValueTuple)
		{
			public static ValueTuple<T1> Zero<T1>()	where T1 : INumberBase<T1> => ValueTuple.Create(T1.Zero);
			public static ValueTuple<T1, T2> Zero<T1, T2>() where T1 : INumberBase<T1> where T2 : INumberBase<T2> => ValueTuple.Create(T1.Zero, 	T2.Zero);
			public static ValueTuple<T1, T2, T3> Zero<T1, T2, T3>() where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> => ValueTuple.Create(T1.Zero, T2.Zero, T3.Zero);
			public static ValueTuple<T1, T2, T3, T4, T5> Zero<T1, T2, T3, T4, T5>() where T1 : INumberBase<T1>	where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> => ValueTuple.Create(T1.Zero,T2.Zero,T3.Zero,T4.Zero,T5.Zero);
			public static ValueTuple<T1, T2, T3, T4, T5, T6> Zero<T1, T2, T3, T4, T5, T6>()	where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> => ValueTuple.Create(T1.Zero, T2.Zero, T3.Zero, T4.Zero, T5.Zero, T6.Zero);
			public static ValueTuple<T1, T2, T3, T4, T5, T6, T7> Zero<T1, T2, T3, T4, T5, T6, T7>() where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> where T7 : INumberBase<T7> => ValueTuple.Create(T1.Zero, T2.Zero, T3.Zero, T4.Zero,T5.Zero, T6.Zero, T7.Zero);
		

			public static ValueTuple<T1> One<T1>() where T1 : INumberBase<T1> => ValueTuple.Create(T1.One);
			public static ValueTuple<T1, T2> One<T1, T2>() where T1 : INumberBase<T1> where T2 : INumberBase<T2> => ValueTuple.Create(T1.One, T2.One);
			public static ValueTuple<T1, T2, T3> One<T1, T2, T3>() where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> => ValueTuple.Create(T1.One, T2.One, T3.One);
			public static ValueTuple<T1, T2, T3, T4, T5> One<T1, T2, T3, T4, T5>() where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> => ValueTuple.Create(T1.One, T2.One, T3.One, T4.One, T5.One);
			public static ValueTuple<T1, T2, T3, T4, T5, T6> One<T1, T2, T3, T4, T5, T6>() where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> => ValueTuple.Create(T1.One, T2.One, T3.One, T4.One, T5.One, T6.One);
		
			public static ValueTuple<T1> Abs<T1>(ValueTuple<T1> a) where T1 : INumberBase<T1> => ValueTuple.Create(T1.Abs(a.Item1));
			public static ValueTuple<T1, T2> Abs<T1, T2>(ValueTuple<T1, T2> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> => ValueTuple.Create(T1.Abs(a.Item1), T2.Abs(a.Item2));
			public static ValueTuple<T1, T2, T3> Abs<T1, T2, T3>(ValueTuple<T1, T2, T3> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> => ValueTuple.Create(T1.Abs(a.Item1), T2.Abs(a.Item2), T3.Abs(a.Item3));
			public static ValueTuple<T1, T2, T3, T4, T5> Abs<T1, T2, T3, T4, T5>(ValueTuple<T1, T2, T3, T4, T5> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> => ValueTuple.Create(T1.Abs(a.Item1), T2.Abs(a.Item2), T3.Abs(a.Item3), T4.Abs(a.Item4), T5.Abs(a.Item5));
			public static ValueTuple<T1, T2, T3, T4, T5, T6> Abs<T1, T2, T3, T4, T5, T6>(ValueTuple<T1, T2, T3, T4, T5, T6> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> => ValueTuple.Create(T1.Abs(a.Item1), T2.Abs(a.Item2), T3.Abs(a.Item3), T4.Abs(a.Item4), T5.Abs(a.Item5), T6.Abs(a.Item6));
			public static ValueTuple<T1, T2, T3, T4, T5, T6, T7> Abs<T1, T2, T3, T4, T5, T6, T7>(ValueTuple<T1, T2, T3, T4, T5, T6, T7> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> where T7 : INumberBase<T7> => ValueTuple.Create(T1.Abs(a.Item1), T2.Abs(a.Item2), T3.Abs(a.Item3), T4.Abs(a.Item4), T5.Abs(a.Item5), T6.Abs(a.Item6), T7.Abs(a.Item7));
		

			
			public static ValueTuple<bool> IsNegative<T1>(ValueTuple<T1> a) where T1 : INumberBase<T1> => ValueTuple.Create(T1.IsNegative(a.Item1));
			public static ValueTuple<bool, bool> IsNegative<T1, T2>(ValueTuple<T1, T2> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> => ValueTuple.Create(T1.IsNegative(a.Item1), T2.IsNegative(a.Item2));
			public static ValueTuple<bool, bool, bool> IsNegative<T1, T2, T3>(ValueTuple<T1, T2, T3> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> => ValueTuple.Create(T1.IsNegative(a.Item1), T2.IsNegative(a.Item2), T3.IsNegative(a.Item3));
			public static ValueTuple<bool, bool, bool, bool> IsNegative<T1, T2, T3, T4>(ValueTuple<T1, T2, T3, T4> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> => ValueTuple.Create(T1.IsNegative(a.Item1), T2.IsNegative(a.Item2), T3.IsNegative(a.Item3), T4.IsNegative(a.Item4));
			public static ValueTuple<bool, bool, bool, bool, bool> IsNegative<T1, T2, T3, T4, T5>(ValueTuple<T1, T2, T3, T4, T5> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> => ValueTuple.Create(T1.IsNegative(a.Item1), T2.IsNegative(a.Item2), T3.IsNegative(a.Item3), T4.IsNegative(a.Item4), T5.IsNegative(a.Item5));
			public static ValueTuple<bool, bool, bool, bool, bool, bool> IsNegative<T1, T2, T3, T4, T5, T6>(ValueTuple<T1, T2, T3, T4, T5, T6> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> => ValueTuple.Create(T1.IsNegative(a.Item1), T2.IsNegative(a.Item2), T3.IsNegative(a.Item3), T4.IsNegative(a.Item4), T5.IsNegative(a.Item5), T6.IsNegative(a.Item6));
			public static ValueTuple<bool, bool, bool, bool, bool, bool, bool> IsNegative<T1, T2, T3, T4, T5, T6, T7>(ValueTuple<T1, T2, T3, T4, T5, T6, T7> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> where T7 : INumberBase<T7> => ValueTuple.Create(T1.IsNegative(a.Item1), T2.IsNegative(a.Item2), T3.IsNegative(a.Item3), T4.IsNegative(a.Item4), T5.IsNegative(a.Item5), T6.IsNegative(a.Item6), T7.IsNegative(a.Item7));

			public static ValueTuple<bool> IsPositive<T1>(ValueTuple<T1> a) where T1 : INumberBase<T1> => ValueTuple.Create(T1.IsPositive(a.Item1));
			public static ValueTuple<bool, bool> IsPositive<T1, T2>(ValueTuple<T1, T2> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> => ValueTuple.Create(T1.IsPositive(a.Item1), T2.IsPositive(a.Item2));
			public static ValueTuple<bool, bool, bool> IsPositive<T1, T2, T3>(ValueTuple<T1, T2, T3> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> => ValueTuple.Create(T1.IsPositive(a.Item1), T2.IsPositive(a.Item2), T3.IsPositive(a.Item3));
			public static ValueTuple<bool, bool, bool, bool> IsPositive<T1, T2, T3, T4>(ValueTuple<T1, T2, T3, T4> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> => ValueTuple.Create(T1.IsPositive(a.Item1), T2.IsPositive(a.Item2), T3.IsPositive(a.Item3), T4.IsPositive(a.Item4));
			public static ValueTuple<bool, bool, bool, bool, bool> IsPositive<T1, T2, T3, T4, T5>(ValueTuple<T1, T2, T3, T4, T5> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> => ValueTuple.Create(T1.IsPositive(a.Item1), T2.IsPositive(a.Item2), T3.IsPositive(a.Item3), T4.IsPositive(a.Item4), T5.IsPositive(a.Item5));
			public static ValueTuple<bool, bool, bool, bool, bool, bool> IsPositive<T1, T2, T3, T4, T5, T6>(ValueTuple<T1, T2, T3, T4, T5, T6> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> => ValueTuple.Create(T1.IsPositive(a.Item1), T2.IsPositive(a.Item2), T3.IsPositive(a.Item3), T4.IsPositive(a.Item4), T5.IsPositive(a.Item5), T6.IsPositive(a.Item6));
			public static ValueTuple<bool, bool, bool, bool, bool, bool, bool> IsPositive<T1, T2, T3, T4, T5, T6, T7>(ValueTuple<T1, T2, T3, T4, T5, T6, T7> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> where T7 : INumberBase<T7> => ValueTuple.Create(T1.IsPositive(a.Item1), T2.IsPositive(a.Item2), T3.IsPositive(a.Item3), T4.IsPositive(a.Item4), T5.IsPositive(a.Item5), T6.IsPositive(a.Item6), T7.IsPositive(a.Item7));

			public static ValueTuple<bool> IsZero<T1>(ValueTuple<T1> a) where T1 : INumberBase<T1> => ValueTuple.Create(T1.IsZero(a.Item1));
			public static ValueTuple<bool, bool> IsZero<T1, T2>(ValueTuple<T1, T2> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> => ValueTuple.Create(T1.IsZero(a.Item1), T2.IsZero(a.Item2));
			public static ValueTuple<bool, bool, bool> IsZero<T1, T2, T3>(ValueTuple<T1, T2, T3> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> => ValueTuple.Create(T1.IsZero(a.Item1), T2.IsZero(a.Item2), T3.IsZero(a.Item3));
			public static ValueTuple<bool, bool, bool, bool> IsZero<T1, T2, T3, T4>(ValueTuple<T1, T2, T3, T4> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> => ValueTuple.Create(T1.IsZero(a.Item1), T2.IsZero(a.Item2), T3.IsZero(a.Item3), T4.IsZero(a.Item4));
			public static ValueTuple<bool, bool, bool, bool, bool> IsZero<T1, T2, T3, T4, T5>(ValueTuple<T1, T2, T3, T4, T5> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> => ValueTuple.Create(T1.IsZero(a.Item1), T2.IsZero(a.Item2), T3.IsZero(a.Item3), T4.IsZero(a.Item4), T5.IsZero(a.Item5));
			public static ValueTuple<bool, bool, bool, bool, bool, bool> IsZero<T1, T2, T3, T4, T5, T6>(ValueTuple<T1, T2, T3, T4, T5, T6> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> => ValueTuple.Create(T1.IsZero(a.Item1), T2.IsZero(a.Item2), T3.IsZero(a.Item3), T4.IsZero(a.Item4), T5.IsZero(a.Item5), T6.IsZero(a.Item6));
			public static ValueTuple<bool, bool, bool, bool, bool, bool, bool> IsZero<T1, T2, T3, T4, T5, T6, T7>(ValueTuple<T1, T2, T3, T4, T5, T6, T7> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> where T7 : INumberBase<T7> => ValueTuple.Create(T1.IsZero(a.Item1), T2.IsZero(a.Item2), T3.IsZero(a.Item3), T4.IsZero(a.Item4), T5.IsZero(a.Item5), T6.IsZero(a.Item6), T7.IsZero(a.Item7));

			public static ValueTuple<bool> IsFinite<T1>(ValueTuple<T1> a) where T1 : INumberBase<T1> => ValueTuple.Create(T1.IsFinite(a.Item1));
			public static ValueTuple<bool, bool> IsFinite<T1, T2>(ValueTuple<T1, T2> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> => ValueTuple.Create(T1.IsFinite(a.Item1), T2.IsFinite(a.Item2));
			public static ValueTuple<bool, bool, bool> IsFinite<T1, T2, T3>(ValueTuple<T1, T2, T3> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> => ValueTuple.Create(T1.IsFinite(a.Item1), T2.IsFinite(a.Item2), T3.IsFinite(a.Item3));
			public static ValueTuple<bool, bool, bool, bool> IsFinite<T1, T2, T3, T4>(ValueTuple<T1, T2, T3, T4> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> => ValueTuple.Create(T1.IsFinite(a.Item1), T2.IsFinite(a.Item2), T3.IsFinite(a.Item3), T4.IsFinite(a.Item4));
			public static ValueTuple<bool, bool, bool, bool, bool> IsFinite<T1, T2, T3, T4, T5>(ValueTuple<T1, T2, T3, T4, T5> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> => ValueTuple.Create(T1.IsFinite(a.Item1), T2.IsFinite(a.Item2), T3.IsFinite(a.Item3), T4.IsFinite(a.Item4), T5.IsFinite(a.Item5));
			public static ValueTuple<bool, bool, bool, bool, bool, bool> IsFinite<T1, T2, T3, T4, T5, T6>(ValueTuple<T1, T2, T3, T4, T5, T6> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> => ValueTuple.Create(T1.IsFinite(a.Item1), T2.IsFinite(a.Item2), T3.IsFinite(a.Item3), T4.IsFinite(a.Item4), T5.IsFinite(a.Item5), T6.IsFinite(a.Item6));
			public static ValueTuple<bool, bool, bool, bool, bool, bool, bool> IsFinite<T1, T2, T3, T4, T5, T6, T7>(ValueTuple<T1, T2, T3, T4, T5, T6, T7> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> where T7 : INumberBase<T7> => ValueTuple.Create(T1.IsFinite(a.Item1), T2.IsFinite(a.Item2), T3.IsFinite(a.Item3), T4.IsFinite(a.Item4), T5.IsFinite(a.Item5), T6.IsFinite(a.Item6), T7.IsFinite(a.Item7));

			public static ValueTuple<bool> IsInfinity<T1>(ValueTuple<T1> a) where T1 : INumberBase<T1> => ValueTuple.Create(T1.IsInfinity(a.Item1));
			public static ValueTuple<bool, bool> IsInfinity<T1, T2>(ValueTuple<T1, T2> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> => ValueTuple.Create(T1.IsInfinity(a.Item1), T2.IsInfinity(a.Item2));
			public static ValueTuple<bool, bool, bool> IsInfinity<T1, T2, T3>(ValueTuple<T1, T2, T3> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> => ValueTuple.Create(T1.IsInfinity(a.Item1), T2.IsInfinity(a.Item2), T3.IsInfinity(a.Item3));
			public static ValueTuple<bool, bool, bool, bool> IsInfinity<T1, T2, T3, T4>(ValueTuple<T1, T2, T3, T4> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> => ValueTuple.Create(T1.IsInfinity(a.Item1), T2.IsInfinity(a.Item2), T3.IsInfinity(a.Item3), T4.IsInfinity(a.Item4));
			public static ValueTuple<bool, bool, bool, bool, bool> IsInfinity<T1, T2, T3, T4, T5>(ValueTuple<T1, T2, T3, T4, T5> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> => ValueTuple.Create(T1.IsInfinity(a.Item1), T2.IsInfinity(a.Item2), T3.IsInfinity(a.Item3), T4.IsInfinity(a.Item4), T5.IsInfinity(a.Item5));
			public static ValueTuple<bool, bool, bool, bool, bool, bool> IsInfinity<T1, T2, T3, T4, T5, T6>(ValueTuple<T1, T2, T3, T4, T5, T6> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> => ValueTuple.Create(T1.IsInfinity(a.Item1), T2.IsInfinity(a.Item2), T3.IsInfinity(a.Item3), T4.IsInfinity(a.Item4), T5.IsInfinity(a.Item5), T6.IsInfinity(a.Item6));
			public static ValueTuple<bool, bool, bool, bool, bool, bool, bool> IsInfinity<T1, T2, T3, T4, T5, T6, T7>(ValueTuple<T1, T2, T3, T4, T5, T6, T7> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> where T7 : INumberBase<T7> => ValueTuple.Create(T1.IsInfinity(a.Item1), T2.IsInfinity(a.Item2), T3.IsInfinity(a.Item3), T4.IsInfinity(a.Item4), T5.IsInfinity(a.Item5), T6.IsInfinity(a.Item6), T7.IsInfinity(a.Item7));

			public static ValueTuple<bool> IsNegativeInfinity<T1>(ValueTuple<T1> a) where T1 : INumberBase<T1> => ValueTuple.Create(T1.IsNegativeInfinity(a.Item1));
			public static ValueTuple<bool, bool> IsNegativeInfinity<T1, T2>(ValueTuple<T1, T2> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> => ValueTuple.Create(T1.IsNegativeInfinity(a.Item1), T2.IsNegativeInfinity(a.Item2));
			public static ValueTuple<bool, bool, bool> IsNegativeInfinity<T1, T2, T3>(ValueTuple<T1, T2, T3> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> => ValueTuple.Create(T1.IsNegativeInfinity(a.Item1), T2.IsNegativeInfinity(a.Item2), T3.IsNegativeInfinity(a.Item3));
			public static ValueTuple<bool, bool, bool, bool> IsNegativeInfinity<T1, T2, T3, T4>(ValueTuple<T1, T2, T3, T4> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> => ValueTuple.Create(T1.IsNegativeInfinity(a.Item1), T2.IsNegativeInfinity(a.Item2), T3.IsNegativeInfinity(a.Item3), T4.IsNegativeInfinity(a.Item4));
			public static ValueTuple<bool, bool, bool, bool, bool> IsNegativeInfinity<T1, T2, T3, T4, T5>(ValueTuple<T1, T2, T3, T4, T5> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> => ValueTuple.Create(T1.IsNegativeInfinity(a.Item1), T2.IsNegativeInfinity(a.Item2), T3.IsNegativeInfinity(a.Item3), T4.IsNegativeInfinity(a.Item4), T5.IsNegativeInfinity(a.Item5));
			public static ValueTuple<bool, bool, bool, bool, bool, bool> IsNegativeInfinity<T1, T2, T3, T4, T5, T6>(ValueTuple<T1, T2, T3, T4, T5, T6> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> => ValueTuple.Create(T1.IsNegativeInfinity(a.Item1), T2.IsNegativeInfinity(a.Item2), T3.IsNegativeInfinity(a.Item3), T4.IsNegativeInfinity(a.Item4), T5.IsNegativeInfinity(a.Item5), T6.IsNegativeInfinity(a.Item6));
			public static ValueTuple<bool, bool, bool, bool, bool, bool, bool> IsNegativeInfinity<T1, T2, T3, T4, T5, T6, T7>(ValueTuple<T1, T2, T3, T4, T5, T6, T7> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> where T7 : INumberBase<T7> => ValueTuple.Create(T1.IsNegativeInfinity(a.Item1), T2.IsNegativeInfinity(a.Item2), T3.IsNegativeInfinity(a.Item3), T4.IsNegativeInfinity(a.Item4), T5.IsNegativeInfinity(a.Item5), T6.IsNegativeInfinity(a.Item6), T7.IsNegativeInfinity(a.Item7));

			public static ValueTuple<bool> IsPositiveInfinity<T1>(ValueTuple<T1> a) where T1 : INumberBase<T1> => ValueTuple.Create(T1.IsPositiveInfinity(a.Item1));
			public static ValueTuple<bool, bool> IsPositiveInfinity<T1, T2>(ValueTuple<T1, T2> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> => ValueTuple.Create(T1.IsPositiveInfinity(a.Item1), T2.IsPositiveInfinity(a.Item2));
			public static ValueTuple<bool, bool, bool> IsPositiveInfinity<T1, T2, T3>(ValueTuple<T1, T2, T3> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> => ValueTuple.Create(T1.IsPositiveInfinity(a.Item1), T2.IsPositiveInfinity(a.Item2), T3.IsPositiveInfinity(a.Item3));
			public static ValueTuple<bool, bool, bool, bool> IsPositiveInfinity<T1, T2, T3, T4>(ValueTuple<T1, T2, T3, T4> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> => ValueTuple.Create(T1.IsPositiveInfinity(a.Item1), T2.IsPositiveInfinity(a.Item2), T3.IsPositiveInfinity(a.Item3), T4.IsPositiveInfinity(a.Item4));
			public static ValueTuple<bool, bool, bool, bool, bool> IsPositiveInfinity<T1, T2, T3, T4, T5>(ValueTuple<T1, T2, T3, T4, T5> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> => ValueTuple.Create(T1.IsPositiveInfinity(a.Item1), T2.IsPositiveInfinity(a.Item2), T3.IsPositiveInfinity(a.Item3), T4.IsPositiveInfinity(a.Item4), T5.IsPositiveInfinity(a.Item5));
			public static ValueTuple<bool, bool, bool, bool, bool, bool> IsPositiveInfinity<T1, T2, T3, T4, T5, T6>(ValueTuple<T1, T2, T3, T4, T5, T6> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> => ValueTuple.Create(T1.IsPositiveInfinity(a.Item1), T2.IsPositiveInfinity(a.Item2), T3.IsPositiveInfinity(a.Item3), T4.IsPositiveInfinity(a.Item4), T5.IsPositiveInfinity(a.Item5), T6.IsPositiveInfinity(a.Item6));
			public static ValueTuple<bool, bool, bool, bool, bool, bool, bool> IsPositiveInfinity<T1, T2, T3, T4, T5, T6, T7>(ValueTuple<T1, T2, T3, T4, T5, T6, T7> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> where T7 : INumberBase<T7> => ValueTuple.Create(T1.IsPositiveInfinity(a.Item1), T2.IsPositiveInfinity(a.Item2), T3.IsPositiveInfinity(a.Item3), T4.IsPositiveInfinity(a.Item4), T5.IsPositiveInfinity(a.Item5), T6.IsPositiveInfinity(a.Item6), T7.IsPositiveInfinity(a.Item7));


			public static ValueTuple<bool> IsComplex<T1>(ValueTuple<T1> a) where T1 : INumberBase<T1> => ValueTuple.Create(T1.IsComplexNumber(a.Item1));
			public static ValueTuple<bool, bool> IsComplex<T1, T2>(ValueTuple<T1, T2> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> => ValueTuple.Create(T1.IsComplexNumber(a.Item1), T2.IsComplexNumber(a.Item2));
			public static ValueTuple<bool, bool, bool> IsComplex<T1, T2, T3>(ValueTuple<T1, T2, T3> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> => ValueTuple.Create(T1.IsComplexNumber(a.Item1), T2.IsComplexNumber(a.Item2), T3.IsComplexNumber(a.Item3));
			public static ValueTuple<bool, bool, bool, bool> IsComplex<T1, T2, T3, T4, T5>(ValueTuple<T1, T2, T3, T4> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> => ValueTuple.Create(T1.IsComplexNumber(a.Item1), T2.IsComplexNumber(a.Item2), T3.IsComplexNumber(a.Item3), T4.IsComplexNumber(a.Item4));
			public static ValueTuple<bool, bool, bool, bool, bool> IsComplex<T1, T2, T3, T4, T5>(ValueTuple<T1, T2, T3, T4, T5> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> => ValueTuple.Create(T1.IsComplexNumber(a.Item1), T2.IsComplexNumber(a.Item2), T3.IsComplexNumber(a.Item3), T4.IsComplexNumber(a.Item4), T5.IsComplexNumber(a.Item5));
			public static ValueTuple<bool, bool, bool, bool, bool, bool> IsComplex<T1, T2, T3, T4, T5, T6>(ValueTuple<T1, T2, T3, T4, T5, T6> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> => ValueTuple.Create(T1.IsComplexNumber(a.Item1), T2.IsComplexNumber(a.Item2), T3.IsComplexNumber(a.Item3), T4.IsComplexNumber(a.Item4), T5.IsComplexNumber(a.Item5), T6.IsComplexNumber(a.Item6));
			public static ValueTuple<bool, bool, bool, bool, bool, bool, bool> IsComplex<T1, T2, T3, T4, T5, T6, T7>(ValueTuple<T1, T2, T3, T4, T5, T6, T7> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> where T7 : INumberBase<T7> => ValueTuple.Create(T1.IsComplexNumber(a.Item1), T2.IsComplexNumber(a.Item2), T3.IsComplexNumber(a.Item3), T4.IsComplexNumber(a.Item4), T5.IsComplexNumber(a.Item5), T6.IsComplexNumber(a.Item6), T7.IsComplexNumber(a.Item7));


			public static ValueTuple<bool> IsReal<T1>(ValueTuple<T1> a) where T1 : INumberBase<T1> => ValueTuple.Create(T1.IsRealNumber(a.Item1));
			public static ValueTuple<bool, bool> IsReal<T1, T2>(ValueTuple<T1, T2> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> => ValueTuple.Create(T1.IsRealNumber(a.Item1), T2.IsRealNumber(a.Item2));
			public static ValueTuple<bool, bool, bool> IsReal<T1, T2, T3>(ValueTuple<T1, T2, T3> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> => ValueTuple.Create(T1.IsRealNumber(a.Item1), T2.IsRealNumber(a.Item2), T3.IsRealNumber(a.Item3));
			public static ValueTuple<bool, bool, bool, bool> IsReal<T1, T2, T3, T4>(ValueTuple<T1, T2, T3, T4> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> => ValueTuple.Create(T1.IsRealNumber(a.Item1), T2.IsRealNumber(a.Item2), T3.IsRealNumber(a.Item3), T4.IsRealNumber(a.Item4));
			public static ValueTuple<bool, bool, bool, bool, bool> IsReal<T1, T2, T3, T4, T5>(ValueTuple<T1, T2, T3, T4, T5> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> => ValueTuple.Create(T1.IsRealNumber(a.Item1), T2.IsRealNumber(a.Item2), T3.IsRealNumber(a.Item3), T4.IsRealNumber(a.Item4), T5.IsRealNumber(a.Item5));
			public static ValueTuple<bool, bool, bool, bool, bool, bool> IsReal<T1, T2, T3, T4, T5, T6>(ValueTuple<T1, T2, T3, T4, T5, T6> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> => ValueTuple.Create(T1.IsRealNumber(a.Item1), T2.IsRealNumber(a.Item2), T3.IsRealNumber(a.Item3), T4.IsRealNumber(a.Item4), T5.IsRealNumber(a.Item5), T6.IsRealNumber(a.Item6));
			public static ValueTuple<bool, bool, bool, bool, bool, bool, bool> IsReal<T1, T2, T3, T4, T5, T6, T7>(ValueTuple<T1, T2, T3, T4, T5, T6, T7> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> where T7 : INumberBase<T7> => ValueTuple.Create(T1.IsRealNumber(a.Item1), T2.IsRealNumber(a.Item2), T3.IsRealNumber(a.Item3), T4.IsRealNumber(a.Item4), T5.IsRealNumber(a.Item5), T6.IsRealNumber(a.Item6), T7.IsRealNumber(a.Item7));

			public static ValueTuple<bool> IsInteger<T1>(ValueTuple<T1> a) where T1 : INumberBase<T1> => ValueTuple.Create(T1.IsInteger(a.Item1));
			public static ValueTuple<bool, bool> IsInteger<T1, T2>(ValueTuple<T1, T2> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> => ValueTuple.Create(T1.IsInteger(a.Item1), T2.IsInteger(a.Item2));
			public static ValueTuple<bool, bool, bool> IsInteger<T1, T2, T3>(ValueTuple<T1, T2, T3> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> => ValueTuple.Create(T1.IsInteger(a.Item1), T2.IsInteger(a.Item2), T3.IsInteger(a.Item3));
			public static ValueTuple<bool, bool, bool, bool> IsInteger<T1, T2, T3, T4>(ValueTuple<T1, T2, T3, T4> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> => ValueTuple.Create(T1.IsInteger(a.Item1), T2.IsInteger(a.Item2), T3.IsInteger(a.Item3), T4.IsInteger(a.Item4));
			public static ValueTuple<bool, bool, bool, bool, bool> IsInteger<T1, T2, T3, T4, T5>(ValueTuple<T1, T2, T3, T4, T5> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> => ValueTuple.Create(T1.IsInteger(a.Item1), T2.IsInteger(a.Item2), T3.IsInteger(a.Item3), T4.IsInteger(a.Item4), T5.IsInteger(a.Item5));
			public static ValueTuple<bool, bool, bool, bool, bool, bool> IsInteger<T1, T2, T3, T4, T5, T6>(ValueTuple<T1, T2, T3, T4, T5, T6> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> => ValueTuple.Create(T1.IsInteger(a.Item1), T2.IsInteger(a.Item2), T3.IsInteger(a.Item3), T4.IsInteger(a.Item4), T5.IsInteger(a.Item5), T6.IsInteger(a.Item6));
			public static ValueTuple<bool, bool, bool, bool, bool, bool, bool> IsInteger<T1, T2, T3, T4, T5, T6, T7>(ValueTuple<T1, T2, T3, T4, T5, T6, T7> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> where T7 : INumberBase<T7> => ValueTuple.Create(T1.IsInteger(a.Item1), T2.IsInteger(a.Item2), T3.IsInteger(a.Item3), T4.IsInteger(a.Item4), T5.IsInteger(a.Item5), T6.IsInteger(a.Item6), T7.IsInteger(a.Item7));

			public static ValueTuple<bool> IsEvenInteger<T1>(ValueTuple<T1> a) where T1 : INumberBase<T1> => ValueTuple.Create(T1.IsEvenInteger(a.Item1));
			public static ValueTuple<bool, bool> IsEvenInteger<T1, T2>(ValueTuple<T1, T2> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> => ValueTuple.Create(T1.IsEvenInteger(a.Item1), T2.IsEvenInteger(a.Item2));
			public static ValueTuple<bool, bool, bool> IsEvenInteger<T1, T2, T3>(ValueTuple<T1, T2, T3> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> => ValueTuple.Create(T1.IsEvenInteger(a.Item1), T2.IsEvenInteger(a.Item2), T3.IsEvenInteger(a.Item3));
			public static ValueTuple<bool, bool, bool, bool> IsEvenInteger<T1, T2, T3, T4>(ValueTuple<T1, T2, T3, T4> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> => ValueTuple.Create(T1.IsEvenInteger(a.Item1), T2.IsEvenInteger(a.Item2), T3.IsEvenInteger(a.Item3), T4.IsEvenInteger(a.Item4));
			public static ValueTuple<bool, bool, bool, bool, bool> IsEvenInteger<T1, T2, T3, T4, T5>(ValueTuple<T1, T2, T3, T4, T5> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> => ValueTuple.Create(T1.IsEvenInteger(a.Item1), T2.IsEvenInteger(a.Item2), T3.IsEvenInteger(a.Item3), T4.IsEvenInteger(a.Item4), T5.IsEvenInteger(a.Item5));
			public static ValueTuple<bool, bool, bool, bool, bool, bool> IsEvenInteger<T1, T2, T3, T4, T5, T6>(ValueTuple<T1, T2, T3, T4, T5, T6> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> => ValueTuple.Create(T1.IsEvenInteger(a.Item1), T2.IsEvenInteger(a.Item2), T3.IsEvenInteger(a.Item3), T4.IsEvenInteger(a.Item4), T5.IsEvenInteger(a.Item5), T6.IsEvenInteger(a.Item6));
			public static ValueTuple<bool, bool, bool, bool, bool, bool, bool> IsEvenInteger<T1, T2, T3, T4, T5, T6, T7>(ValueTuple<T1, T2, T3, T4, T5, T6, T7> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> where T7 : INumberBase<T7> => ValueTuple.Create(T1.IsEvenInteger(a.Item1), T2.IsEvenInteger(a.Item2), T3.IsEvenInteger(a.Item3), T4.IsEvenInteger(a.Item4), T5.IsEvenInteger(a.Item5), T6.IsEvenInteger(a.Item6), T7.IsEvenInteger(a.Item7));


			public static ValueTuple<bool> IsOddInteger<T1>(ValueTuple<T1> a) where T1 : INumberBase<T1> => ValueTuple.Create(T1.IsOddInteger(a.Item1));
			public static ValueTuple<bool, bool> IsOddInteger<T1, T2>(ValueTuple<T1, T2> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> => ValueTuple.Create(T1.IsOddInteger(a.Item1), T2.IsOddInteger(a.Item2));
			public static ValueTuple<bool, bool, bool> IsOddInteger<T1, T2, T3>(ValueTuple<T1, T2, T3> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> => ValueTuple.Create(T1.IsOddInteger(a.Item1), T2.IsOddInteger(a.Item2), T3.IsOddInteger(a.Item3));
			public static ValueTuple<bool, bool, bool, bool> IsOddInteger<T1, T2, T3, T4>(ValueTuple<T1, T2, T3, T4> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> => ValueTuple.Create(T1.IsOddInteger(a.Item1), T2.IsOddInteger(a.Item2), T3.IsOddInteger(a.Item3), T4.IsOddInteger(a.Item4));
			public static ValueTuple<bool, bool, bool, bool, bool> IsOddInteger<T1, T2, T3, T4, T5>(ValueTuple<T1, T2, T3, T4, T5> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> => ValueTuple.Create(T1.IsOddInteger(a.Item1), T2.IsOddInteger(a.Item2), T3.IsOddInteger(a.Item3), T4.IsOddInteger(a.Item4), T5.IsOddInteger(a.Item5));
			public static ValueTuple<bool, bool, bool, bool, bool, bool> IsOddInteger<T1, T2, T3, T4, T5, T6>(ValueTuple<T1, T2, T3, T4, T5, T6> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> => ValueTuple.Create(T1.IsOddInteger(a.Item1), T2.IsOddInteger(a.Item2), T3.IsOddInteger(a.Item3), T4.IsOddInteger(a.Item4), T5.IsOddInteger(a.Item5), T6.IsOddInteger(a.Item6));
			public static ValueTuple<bool, bool, bool, bool, bool, bool, bool> IsOddInteger<T1, T2, T3, T4, T5, T6, T7>(ValueTuple<T1, T2, T3, T4, T5, T6, T7> a) where T1 : INumberBase<T1> where T2 : INumberBase<T2> where T3 : INumberBase<T3> where T4 : INumberBase<T4> where T5 : INumberBase<T5> where T6 : INumberBase<T6> where T7 : INumberBase<T7> => ValueTuple.Create(T1.IsOddInteger(a.Item1), T2.IsOddInteger(a.Item2), T3.IsOddInteger(a.Item3), T4.IsOddInteger(a.Item4), T5.IsOddInteger(a.Item5), T6.IsOddInteger(a.Item6), T7.IsOddInteger(a.Item7));

		}
	}

	
}
