namespace Holdem.Core.Internal
{

	internal static partial class DECK
	{
		internal static partial class CARD
		{
			public const int COUNT = RANK.COUNT * SUIT.COUNT;

			public enum ID : int
			{
				TWO_OF_CLUBS		= RANK.ID.TWO		+ RANK.COUNT * SUIT.ID.CLUBS,
				THREE_OF_CLUBS		= RANK.ID.THREE	+ RANK.COUNT * SUIT.ID.CLUBS,
				FOUR_OF_CLUBS		= RANK.ID.FOUR		+ RANK.COUNT * SUIT.ID.CLUBS,
				FIVE_OF_CLUBS		= RANK.ID.FIVE		+ RANK.COUNT * SUIT.ID.CLUBS,
				SIX_OF_CLUBS		= RANK.ID.SIX		+ RANK.COUNT * SUIT.ID.CLUBS,
				SEVEN_OF_CLUBS		= RANK.ID.SEVEN	+ RANK.COUNT * SUIT.ID.CLUBS,
				EIGHT_OF_CLUBS		= RANK.ID.EIGHT	+ RANK.COUNT * SUIT.ID.CLUBS,
				NINE_OF_CLUBS		= RANK.ID.NINE		+ RANK.COUNT * SUIT.ID.CLUBS,
				TEN_OF_CLUBS		= RANK.ID.TEN		+ RANK.COUNT * SUIT.ID.CLUBS,
				JACK_OF_CLUBS		= RANK.ID.JACK		+ RANK.COUNT * SUIT.ID.CLUBS,
				QUEEN_OF_CLUBS		= RANK.ID.QUEEN	+ RANK.COUNT * SUIT.ID.CLUBS,
				KING_OF_CLUBS		= RANK.ID.KING		+ RANK.COUNT * SUIT.ID.CLUBS,
				ACE_OF_CLUBS		= RANK.ID.ACE		+ RANK.COUNT * SUIT.ID.CLUBS,

				TWO_OF_HEARTS		= RANK.ID.TWO		+ RANK.COUNT * SUIT.ID.HEARTS,
				THREE_OF_HEARTS	= RANK.ID.THREE	+ RANK.COUNT * SUIT.ID.HEARTS,
				FOUR_OF_HEARTS		= RANK.ID.FOUR		+ RANK.COUNT * SUIT.ID.HEARTS,
				FIVE_OF_HEARTS		= RANK.ID.FIVE		+ RANK.COUNT * SUIT.ID.HEARTS,
				SIX_OF_HEARTS		= RANK.ID.SIX		+ RANK.COUNT * SUIT.ID.HEARTS,
				SEVEN_OF_HEARTS	= RANK.ID.SEVEN	+ RANK.COUNT * SUIT.ID.HEARTS,
				EIGHT_OF_HEARTS	= RANK.ID.EIGHT	+ RANK.COUNT * SUIT.ID.HEARTS,
				NINE_OF_HEARTS		= RANK.ID.NINE		+ RANK.COUNT * SUIT.ID.HEARTS,
				TEN_OF_HEARTS		= RANK.ID.TEN		+ RANK.COUNT * SUIT.ID.HEARTS,
				JACK_OF_HEARTS		= RANK.ID.JACK		+ RANK.COUNT * SUIT.ID.HEARTS,
				QUEEN_OF_HEARTS	= RANK.ID.QUEEN	+ RANK.COUNT * SUIT.ID.HEARTS,
				KING_OF_HEARTS		= RANK.ID.KING		+ RANK.COUNT * SUIT.ID.HEARTS,
				ACE_OF_HEARTS		= RANK.ID.ACE		+ RANK.COUNT * SUIT.ID.HEARTS,
				
				TWO_OF_DIAMONDS	= RANK.ID.TWO		+ RANK.COUNT * SUIT.ID.DIAMONDS,
				THREE_OF_DIAMONDS	= RANK.ID.THREE	+ RANK.COUNT * SUIT.ID.DIAMONDS,
				FOUR_OF_DIAMONDS	= RANK.ID.FOUR		+ RANK.COUNT * SUIT.ID.DIAMONDS,
				FIVE_OF_DIAMONDS	= RANK.ID.FIVE		+ RANK.COUNT * SUIT.ID.DIAMONDS,
				SIX_OF_DIAMONDS	= RANK.ID.SIX		+ RANK.COUNT * SUIT.ID.DIAMONDS,
				SEVEN_OF_DIAMONDS	= RANK.ID.SEVEN	+ RANK.COUNT * SUIT.ID.DIAMONDS,
				EIGHT_OF_DIAMONDS	= RANK.ID.EIGHT	+ RANK.COUNT * SUIT.ID.DIAMONDS,
				NINE_OF_DIAMONDS	= RANK.ID.NINE		+ RANK.COUNT * SUIT.ID.DIAMONDS,
				TEN_OF_DIAMONDS	= RANK.ID.TEN		+ RANK.COUNT * SUIT.ID.DIAMONDS,
				JACK_OF_DIAMONDS	= RANK.ID.JACK		+ RANK.COUNT * SUIT.ID.DIAMONDS,
				QUEEN_OF_DIAMONDS	= RANK.ID.QUEEN	+ RANK.COUNT * SUIT.ID.DIAMONDS,
				KING_OF_DIAMONDS	= RANK.ID.KING		+ RANK.COUNT * SUIT.ID.DIAMONDS,
				ACE_OF_DIAMONDS	= RANK.ID.ACE		+ RANK.COUNT * SUIT.ID.DIAMONDS,

				TWO_OF_SPADES		= RANK.ID.TWO		+ RANK.COUNT * SUIT.ID.SPADES,
				THREE_OF_SPADES	= RANK.ID.THREE	+ RANK.COUNT * SUIT.ID.SPADES,
				FOUR_OF_SPADES		= RANK.ID.FOUR		+ RANK.COUNT * SUIT.ID.SPADES,
				FIVE_OF_SPADES		= RANK.ID.FIVE		+ RANK.COUNT * SUIT.ID.SPADES,
				SIX_OF_SPADES		= RANK.ID.SIX		+ RANK.COUNT * SUIT.ID.SPADES,
				SEVEN_OF_SPADES	= RANK.ID.SEVEN	+ RANK.COUNT * SUIT.ID.SPADES,
				EIGHT_OF_SPADES	= RANK.ID.EIGHT	+ RANK.COUNT * SUIT.ID.SPADES,
				NINE_OF_SPADES		= RANK.ID.NINE		+ RANK.COUNT * SUIT.ID.SPADES,
				TEN_OF_SPADES		= RANK.ID.TEN		+ RANK.COUNT * SUIT.ID.SPADES,
				JACK_OF_SPADES		= RANK.ID.JACK		+ RANK.COUNT * SUIT.ID.SPADES,
				QUEEN_OF_SPADES	= RANK.ID.QUEEN	+ RANK.COUNT * SUIT.ID.SPADES,
				KING_OF_SPADES		= RANK.ID.KING		+ RANK.COUNT * SUIT.ID.SPADES,
				ACE_OF_SPADES		= RANK.ID.ACE		+ RANK.COUNT * SUIT.ID.SPADES,
			}

			public enum MASK : uint
			{
				TWO_OF_CLUBS		= RANK.FLAG.TWO	| (SUIT.FLAG.CLUBS << RANK.COUNT),
				THREE_OF_CLUBS		= RANK.FLAG.THREE	| (SUIT.FLAG.CLUBS << RANK.COUNT),
				FOUR_OF_CLUBS		= RANK.FLAG.FOUR	| (SUIT.FLAG.CLUBS << RANK.COUNT),
				FIVE_OF_CLUBS		= RANK.FLAG.FIVE	| (SUIT.FLAG.CLUBS << RANK.COUNT),
				SIX_OF_CLUBS		= RANK.FLAG.SIX	| (SUIT.FLAG.CLUBS << RANK.COUNT),
				SEVEN_OF_CLUBS		= RANK.FLAG.SEVEN	| (SUIT.FLAG.CLUBS << RANK.COUNT),
				EIGHT_OF_CLUBS		= RANK.FLAG.EIGHT	| (SUIT.FLAG.CLUBS << RANK.COUNT),
				NINE_OF_CLUBS		= RANK.FLAG.NINE	| (SUIT.FLAG.CLUBS << RANK.COUNT),
				TEN_OF_CLUBS		= RANK.FLAG.TEN	| (SUIT.FLAG.CLUBS << RANK.COUNT),
				JACK_OF_CLUBS		= RANK.FLAG.JACK	| (SUIT.FLAG.CLUBS << RANK.COUNT),
				QUEEN_OF_CLUBS		= RANK.FLAG.QUEEN	| (SUIT.FLAG.CLUBS << RANK.COUNT),
				KING_OF_CLUBS		= RANK.FLAG.KING	| (SUIT.FLAG.CLUBS << RANK.COUNT),
				ACE_OF_CLUBS		= RANK.FLAG.ACE	| (SUIT.FLAG.CLUBS << RANK.COUNT),

				TWO_OF_HEARTS		= RANK.FLAG.TWO	| (SUIT.FLAG.HEARTS << RANK.COUNT),
				THREE_OF_HEARTS	= RANK.FLAG.THREE	| (SUIT.FLAG.HEARTS << RANK.COUNT),
				FOUR_OF_HEARTS		= RANK.FLAG.FOUR	| (SUIT.FLAG.HEARTS << RANK.COUNT),
				FIVE_OF_HEARTS		= RANK.FLAG.FIVE	| (SUIT.FLAG.HEARTS << RANK.COUNT),
				SIX_OF_HEARTS		= RANK.FLAG.SIX	| (SUIT.FLAG.HEARTS << RANK.COUNT),
				SEVEN_OF_HEARTS	= RANK.FLAG.SEVEN	| (SUIT.FLAG.HEARTS << RANK.COUNT),
				EIGHT_OF_HEARTS	= RANK.FLAG.EIGHT	| (SUIT.FLAG.HEARTS << RANK.COUNT),
				NINE_OF_HEARTS		= RANK.FLAG.NINE	| (SUIT.FLAG.HEARTS << RANK.COUNT),
				TEN_OF_HEARTS		= RANK.FLAG.TEN	| (SUIT.FLAG.HEARTS << RANK.COUNT),
				JACK_OF_HEARTS		= RANK.FLAG.JACK	| (SUIT.FLAG.HEARTS << RANK.COUNT),
				QUEEN_OF_HEARTS	= RANK.FLAG.QUEEN	| (SUIT.FLAG.HEARTS << RANK.COUNT),
				KING_OF_HEARTS		= RANK.FLAG.KING	| (SUIT.FLAG.HEARTS << RANK.COUNT),
				ACE_OF_HEARTS		= RANK.FLAG.ACE	| (SUIT.FLAG.HEARTS << RANK.COUNT),

				TWO_OF_DIAMONDS	= RANK.FLAG.TWO	| (SUIT.FLAG.DIAMONDS << RANK.COUNT),
				THREE_OF_DIAMONDS	= RANK.FLAG.THREE	| (SUIT.FLAG.DIAMONDS << RANK.COUNT),
				FOUR_OF_DIAMONDS	= RANK.FLAG.FOUR	| (SUIT.FLAG.DIAMONDS << RANK.COUNT),
				FIVE_OF_DIAMONDS	= RANK.FLAG.FIVE	| (SUIT.FLAG.DIAMONDS << RANK.COUNT),
				SIX_OF_DIAMONDS	= RANK.FLAG.SIX	| (SUIT.FLAG.DIAMONDS << RANK.COUNT),
				SEVEN_OF_DIAMONDS	= RANK.FLAG.SEVEN	| (SUIT.FLAG.DIAMONDS << RANK.COUNT),
				EIGHT_OF_DIAMONDS	= RANK.FLAG.EIGHT	| (SUIT.FLAG.DIAMONDS << RANK.COUNT),
				NINE_OF_DIAMONDS	= RANK.FLAG.NINE	| (SUIT.FLAG.DIAMONDS << RANK.COUNT),
				TEN_OF_DIAMONDS	= RANK.FLAG.TEN	| (SUIT.FLAG.DIAMONDS << RANK.COUNT),
				JACK_OF_DIAMONDS	= RANK.FLAG.JACK	| (SUIT.FLAG.DIAMONDS << RANK.COUNT),
				QUEEN_OF_DIAMONDS	= RANK.FLAG.QUEEN	| (SUIT.FLAG.DIAMONDS << RANK.COUNT),
				KING_OF_DIAMONDS	= RANK.FLAG.KING	| (SUIT.FLAG.DIAMONDS << RANK.COUNT),
				ACE_OF_DIAMONDS	= RANK.FLAG.ACE	| (SUIT.FLAG.DIAMONDS << RANK.COUNT),

				TWO_OF_SPADES		= RANK.FLAG.TWO	| (SUIT.FLAG.SPADES << RANK.COUNT),
				THREE_OF_SPADES	= RANK.FLAG.THREE	| (SUIT.FLAG.SPADES << RANK.COUNT),
				FOUR_OF_SPADES		= RANK.FLAG.FOUR	| (SUIT.FLAG.SPADES << RANK.COUNT),
				FIVE_OF_SPADES		= RANK.FLAG.FIVE	| (SUIT.FLAG.SPADES << RANK.COUNT),
				SIX_OF_SPADES		= RANK.FLAG.SIX	| (SUIT.FLAG.SPADES << RANK.COUNT),
				SEVEN_OF_SPADES	= RANK.FLAG.SEVEN	| (SUIT.FLAG.SPADES << RANK.COUNT),
				EIGHT_OF_SPADES	= RANK.FLAG.EIGHT	| (SUIT.FLAG.SPADES << RANK.COUNT),
				NINE_OF_SPADES		= RANK.FLAG.NINE	| (SUIT.FLAG.SPADES << RANK.COUNT),
				TEN_OF_SPADES		= RANK.FLAG.TEN	| (SUIT.FLAG.SPADES << RANK.COUNT),
				JACK_OF_SPADES		= RANK.FLAG.JACK	| (SUIT.FLAG.SPADES << RANK.COUNT),
				QUEEN_OF_SPADES	= RANK.FLAG.QUEEN	| (SUIT.FLAG.SPADES << RANK.COUNT),
				KING_OF_SPADES		= RANK.FLAG.KING	| (SUIT.FLAG.SPADES << RANK.COUNT),
				ACE_OF_SPADES		= RANK.FLAG.ACE	| (SUIT.FLAG.SPADES << RANK.COUNT),
			}
		}
	}
}
