<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
		<AssemblyName>MemoryPools</AssemblyName>
		<GenerateAssemblyInfo>False</GenerateAssemblyInfo>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
	</PropertyGroup>
</Project>